import React from 'react';
import Navigation from '../components/Navigation';
import Head from 'next/head';
import Menu from '../components/Menu';
import Banner from '../components/Banner';
import Footer from '../components/Footer';

function about() {
  return <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Navigation />
      <Banner 
        title='We are a small studio that creates results.'
      />
      <Footer />
  </>;
}

export default about;
